export const EXPEDITION_STATUS = {
  ANSWER: 'ANSWER',
  CHOOSE: 'CHOOSE'
}

export const QUESTION_TYPE = {
  NOT_APPLICABLE: null,
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
  OPEN: 'OPENED'
}
